<a href="https://colab.research.google.com/github/Gulshat5510/DeepHeart/blob/AI/heart_attack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/heart attack.csv')
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [2]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
x= data.drop(["output"], axis=1)
y= data['output']
x_train, x_test, y_train, y_test= train_test_split(x,y, random_state=42, test_size=0.2)


In [ ]:
scaler = MinMaxScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train.reshape(-1,1)
x_test.reshape(-1,1)

In [4]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 

In [5]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=0, max_depth=5)
model.fit(x_train, y_train)

y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

print(confusion_matrix(y_train, y_pred_train))
print(confusion_matrix(y_test, y_pred_test))
acc = accuracy_score(y_train, y_pred_train)
print("Accuracy : ", acc)
acc = accuracy_score(y_test, y_pred_test)
print("Accuracy : ", acc)

[[ 90  19]
 [  2 131]]
[[24  5]
 [ 5 27]]
Accuracy :  0.9132231404958677
Accuracy :  0.8360655737704918


In [ ]:
a=model.predict(d.reshape(1,-1))
a

array([1])

In [6]:
import joblib
joblib.dump(model, 'attack_heart.pkl')

['attack_heart.pkl']

In [122]:
!pip install -q streamlit

In [121]:
python3 -m venv tutorial-env

SyntaxError: ignored

In [119]:
!wget https://raw.githubusercontent.com/dataprofessor/code/master/streamlit/iris-ml-app.py

--2022-05-27 13:09:29--  https://raw.githubusercontent.com/dataprofessor/code/master/streamlit/iris-ml-app.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-27 13:09:29 ERROR 404: Not Found.



In [ ]:
c=data.iloc[0].values
d=np.delete(c,-1)

In [ ]:
model.predict(x_test)
b=np.array([16,1,2,130,130,0,1,130,0,1,2,2,2])


In [7]:
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_ngrok import run_with_ngrok