<a href="https://colab.research.google.com/github/Gulshat5510/DeepHeart/blob/AI/Heart_Failure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
heart= pd.read_csv('/content/drive/MyDrive/heart failure.csv')
heart.head()


Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [5]:
heart['Sex']

0      M
1      F
2      M
3      F
4      M
      ..
913    M
914    M
915    M
916    F
917    M
Name: Sex, Length: 918, dtype: object

In [3]:
heart['Sex'].replace(['M', 'F'], [2,1], inplace=True)
heart['ChestPainType'].replace(['TA', 'ATA', 'NAP', 'ASY'], [1,2,3,4], inplace=True)
heart['RestingECG'].replace(['Normal','ST', 'LVH'], [1,2,3], inplace=True)
heart['ExerciseAngina'].replace(['N','Y'], [0,1], inplace=True)
heart['ST_Slope'].replace(['Up', 'Flat','Down'], [1,2,3], inplace=True)


In [4]:
heart.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    2              2        140          289          0           1   
1   49    1              3        160          180          0           1   
2   37    2              2        130          283          0           2   
3   48    1              4        138          214          0           1   
4   54    2              3        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         1             0  
1    156               0      1.0         2             1  
2     98               0      0.0         1             0  
3    108               1      1.5         2             1  
4    122               0      0.0         1             0

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
x= heart.drop(["HeartDisease"], axis=1)
y= heart['HeartDisease']
x_train, x_test, y_train, y_test= train_test_split(x,y, random_state=42, test_size=0.2)


In [6]:
scaler = MinMaxScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train.reshape(-1, 1)
x_test.reshape(-1, 1)

array([[0.70833333],
       [0.        ],
       [0.33333333],
       ...,
       [1.        ],
       [0.40909091],
       [0.5       ]])

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 

In [8]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=0, max_depth=5)
model.fit(x_train, y_train)

y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

print(confusion_matrix(y_train, y_pred_train))
print(confusion_matrix(y_test, y_pred_test))
acc = accuracy_score(y_train, y_pred_train)
print("Accuracy : ", acc)
acc = accuracy_score(y_test, y_pred_test)
print("Accuracy : ", acc)



[[290  43]
 [ 32 369]]
[[67 10]
 [14 93]]
Accuracy :  0.8978201634877384
Accuracy :  0.8695652173913043


In [9]:

import joblib
joblib.dump(model, 'failure_heart.pkl')

['failure_heart.pkl']